# Generated by Django 5.2.11 on 2026-02-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(default=0)),
                ('category', models.CharField(choices=[('stock', 'Stock'), ('index', 'Index')], default='stock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='stocks_stoc_symbol_e1c05b_idx'), models.Index(fields=['symbol', '-date'], name='stocks_stoc_symbol_d20ba8_idx'), models.Index(fields=['-date'], name='stocks_stoc_date_785a6d_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
