# Generated by Django 5.2.11 on 2026-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_downloadlog_scraperlog_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('prev_earnings', models.CharField(blank=True, max_length=50)),
                ('reported_eps', models.CharField(blank=True, max_length=50)),
                ('earnings', models.CharField(blank=True, max_length=50)),
                ('yoy_growth_percent', models.FloatField(blank=True, null=True)),
                ('ttm_eps', models.CharField(blank=True, max_length=50)),
                ('surprise', models.CharField(blank=True, max_length=100)),
                ('publish_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('symbol', 'reported_eps', 'publish_date')},
            },
        ),
    ]
