# Generated by Django 5.2.11 on 2026-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_marketholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlyreport',
            name='earnings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='surprise',
            field=models.TextField(blank=True),
        ),
    ]
